name: flutterdemo
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  get: ^4.6.5
  dio: ^4.0.6
  logger: ^1.1.0
  pull_to_refresh_flutter3: ^2.0.1
  pull_to_refresh_notification: ^2.3.0
  flutter_datetime_picker: ^1.5.1
  flutter_picker: ^2.0.5
  flutter_easy_permission: ^1.1.2
  image_picker: ^0.8.5+3
  flutter_screenutil: ^5.5.4
  connectivity: ^3.0.6
  file_picker: ^5.2.0
  event_bus: ^2.0.0
  flutter_smart_dialog: ^4.5.5+6
  flutter_swiper_null_safety: ^1.0.2
  keframe: ^3.0.0
  extended_image: ^6.3.1
  extended_text_field: ^10.1.1
  extended_tabs: ^3.0.3
  extended_text: ^9.1.2
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
